on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
        with:
          cache: true
          run_install: |
            - args: [--prefer-offline, --frozen-lockfile, --ignore-scripts]
      - uses: actions/cache@v5
        with:
          key: eslint-cache-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('pnpm-lock.yaml', 'eslint.config.ts') }}
          restore-keys: |
            eslint-cache-${{ runner.os }}-${{ runner.arch }}-
          path: |
            .eslintcache
      - run: pnpm check

  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.59.1
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [ 1, 2, 3, 4 ]
        shardTotal: [ 4 ]
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
        with:
          cache: true
          run_install: |
            - args: [--prefer-offline, --frozen-lockfile, --ignore-scripts]
      - run: pnpm exec playwright install chrome msedge
      - run: pnpm build-only --mode e2e
      - run: pnpm test:e2e --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          HOME: /root
          TZ: Europe/Amsterdam
