on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
        with:
          cache: true
          run_install: |
            - args: [--prefer-offline, --frozen-lockfile]
      - run: VITE_APP_VERSION=$(git rev-parse --short HEAD) pnpm build-only
        env:
          APP_BASE: /${{ github.event.repository.name }}/
          VITE_GEOAPIFY_API_KEY: ${{ secrets.GEOAPIFY_API_KEY }}
      - uses: actions/upload-pages-artifact@v4
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
